spring:
  application:
    name: idea

#  ldap:
#    embedded:
#      ldif: classpath:test-server.ldif
#      base-dn: dc=springframework,dc=org
#      port: 8389

  #  Configure default username and password
  security:
    user:
      name: user
      password: root
      role: user

  # Database connection
  datasource:
    url: jdbc:mysql://${app.database.host}:${app.database.port}/${app.database.name}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=FALSE
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${app.database.username}
    password: ${app.database.password}

  jpa:
    # Automatically create tables from entities
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    # Show sql queries made by spring data jpa
    show-sql: false
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: false

  # Show logs in colored mode
  output:
    ansi:
      enabled: ALWAYS

  # Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: olaskeet@gmail.com
    password: flywrsikjtoahtrn
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: false
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

# Configure port
server:
  port:
    8085

app:
  application-name: idea-portal
  application-email: eonyejeme@ecobank.com
  admin-username: oomoriwo@ecobank.com
  base-url: http://localhost
  allowed-origins: http://localhost
#  ldap-url: ldap://localhost:8389/dc=springframework,dc=org
#  ldap:
#    port: 8389
  database:
    name: ideaPortal
    username: root
    password: root
    host: localhost
    port: 3306

# Logging configuration
logging:
  level:
    org:
      springframework:
        security: DEBUG

# Spring doc path
springdoc:
  api-docs:
    path: /docs